# Generated by Django 6.0.7 on 2026-08-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
