# Generated by Django 6.0.7 on 2026-08-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
