# Generated by Django 6.0.7 on 2026-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicinereminder_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carrier_gateway',
            field=models.CharField(blank=True, choices=[('', 'Select carrier'), ('airtelap.com', 'Airtel (India)'), ('ideacellular.net', 'Vi / Vodafone-Idea (India)'), ('sms.bsnlmobile.in', 'BSNL (India)'), ('jio.com', 'Jio (India)'), ('txt.att.net', 'AT&T (US)'), ('tmomail.net', 'T-Mobile (US)'), ('vtext.com', 'Verizon (US)'), ('messaging.sprintpcs.com', 'Sprint (US)'), ('sms.rogers.com', 'Rogers (Canada)'), ('txt.bell.ca', 'Bell (Canada)')], help_text='Used to send SMS via email gateway', max_length=100),
        ),
    ]
