# Generated by Django 6.0.7 on 2026-08-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_carrier_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='last_sms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
